name: winterproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  image_picker: ^1.0.7
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.jpeg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/first.png
    - assets/images/second.png
    - assets/images/third.png
    - assets/images/app_icon.jpeg
