// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0HMK1YwKuhmA--avoEkWrMIFZ9PJPM8Q',
    appId: '1:1005976340899:web:7bb777bce93a3ce189f216',
    messagingSenderId: '1005976340899',
    projectId: 'brandoraapp',
    authDomain: 'brandoraapp.firebaseapp.com',
    storageBucket: 'brandoraapp.firebasestorage.app',
    measurementId: 'G-G75K3V5EF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsuN2R4J4N7tc3jhGpCZuin69Gwm3o9KU',
    appId: '1:1005976340899:android:f7ac7de6a709779f89f216',
    messagingSenderId: '1005976340899',
    projectId: 'brandoraapp',
    storageBucket: 'brandoraapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-iSzBXVAuKScbMbZUkSMgTBKXtl-SWAc',
    appId: '1:1005976340899:ios:e27b552d8e437aa089f216',
    messagingSenderId: '1005976340899',
    projectId: 'brandoraapp',
    storageBucket: 'brandoraapp.firebasestorage.app',
    iosBundleId: 'com.example.winterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-iSzBXVAuKScbMbZUkSMgTBKXtl-SWAc',
    appId: '1:1005976340899:ios:e27b552d8e437aa089f216',
    messagingSenderId: '1005976340899',
    projectId: 'brandoraapp',
    storageBucket: 'brandoraapp.firebasestorage.app',
    iosBundleId: 'com.example.winterproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0HMK1YwKuhmA--avoEkWrMIFZ9PJPM8Q',
    appId: '1:1005976340899:web:ef01ad81fc739fa689f216',
    messagingSenderId: '1005976340899',
    projectId: 'brandoraapp',
    authDomain: 'brandoraapp.firebaseapp.com',
    storageBucket: 'brandoraapp.firebasestorage.app',
    measurementId: 'G-R7D87PFMEZ',
  );
}
